### ISSUE TITLE
CPAN-02Packages-Search-0.002 removed README

### ISSUE THREAD

**Issue by ppisar** [skaji/CPAN-02Packages-Search#1]
CPAN-02Packages-Search-0.002 removed plenty files, on of them is README. As a results <https://metacpan.org/dist/CPAN-02Packages-Search> does not display any description. Is that intentional?

**Comment by skaji** [comment]
That is intentional.
What is "description"?

**Comment by ppisar** [comment]
I see. I thought that MetaCPAN shows README. But it does not (at least now). So there is now problem on MetaCPAN.
However, maybe you could add README.md into the distribution archive. Now it is in git repository, but not in the archive.

**Comment by skaji** [comment]
I don't think README files in CPAN distribution archives are very useful.
I always read pods in module files.

**Comment by ppisar** [comment]
No problem.
